### ISSUE TITLE
GTF file button does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by tweirick** [djhn75/RNAEditor#3] opened 2016-10-26 14:37 UTC
I haven't tested it on other operating systems, so this could happen elsewhere. The button to specify the path to a GTF file doesn't open a window like the other buttons.

**Comment by djhn75** [comment] 2016-10-27 20:20
Thanks, the problem is fixed now...
Thanks Tyler 
[Commit](https://github.com/djhn75/RNAEditor/commit/fa3b56e1664c862271a5a3b2a50796243b2895c8)

**Closed as completed by djhn75** 2016-10-27 20:20 UTC
